kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  namespace: test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    avp.kubernetes.io/path: "ibmcloud/kv/secrets/groups/c3f6942d-41dd-ea66-8f2a-88c3e1e0c04c"
type: Opaque
stringData:
  POSTGRES_USERNAME: <postgresql-credentials-test | jsonPath {.username}>
